version: '3.8'

services:

  ms-event-receiver-api:
    build:
      context: .
      args:
        - APP=ms-event-receiver-api
    container_name: ms-api
    env_file:
      - .env
    depends_on:
      - rabbitmq
    networks:
      - backend
    ports:
      - 3001:3001
    restart: unless-stopped

  ms-event-publisher:
    build:
      context: .
      args:
        - APP=ms-event-publisher
    container_name: ms-event-publisher
    env_file:
      - .env
    depends_on:
      - rabbitmq
    networks:
      - backend
    ports:
      - 3000:3000
    restart: unless-stopped

  ms-event-receiver-data-provider:
    build:
      context: .
      args:
        - APP=ms-event-receiver-data-provider
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - backend
    ports:
      - 3002
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13.7-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: username
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "8080:15672"
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 10s
      retries: 5

  mongo:
    image: mongo:7.0.14
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongo-data:/data/db

networks:
  backend:
    driver: bridge

volumes:
  mongo-data:
    driver: local
