version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13.7-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: username
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '5672:5672'
      - '8080:15672'
    networks:
      - backend
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 10s
      timeout: 10s
      retries: 5

  mongo:
    image: mongo:7.0.14
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      - backend
    volumes:
      - mongo-data:/data/db

networks:
  backend:
    driver: bridge

volumes:
  mongo-data:
    driver: local
